name: Welcome New Contributor

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hello & Welcome! :)
            
            Thanks for taking the time to get in touch.
            
            We ask that all bugs/feature/support requests are raised via the [forum](https://forum.itflow.org). We'll be in touch shortly to confirm.
          pr-message: |
            Hello & Welcome! :)
            
            Thanks for taking the time to help improve ITFlow. We're excited to review your contributions - we'll review this PR as soon as we can!
            
            Whilst you're waiting, please feel free to check out the [forum](https://forum.itflow.org).

            Just so you know, all contributions to ITFlow are licensed under the GNU GPL. By contributing you grant us a perpetual & irrevocable license to include your work in ITFlow.
